
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-ubuntu-deployment
  labels:
    app: demo-ubuntu
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: demo-ubuntu
  template:
    metadata:
      labels:
        app: demo-ubuntu
    spec:
      containers:
      - name: demo-ubuntu
        image: ubuntu
        imagePullPolicy: IfNotPresent

        command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']
