apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-hd1-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/hd1/example"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-hd1-volume
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
